services:
  - type: web
    name: eco-tashkent-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 4000

  - type: worker
    name: eco-tashkent-bot
    env: node
    plan: free
    rootDir: bot
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BACKEND_URL
        sync: false
